### ISSUE TITLE
First-release requirements

### ISSUE THREAD

**Issue by JKetelaar** [Parabot/Launcher#1]
We need the following to be done, to have the first release ready:
- [x] Downloading Parabot into a folder, if not exists
- [x] Locate `java` to allow launching with commands (ie `-noverify`)
- [x] Allow launch of Parabot with commands
- [x] Have a configuration saving method, to save for later usage
- [x] Check if we have the latest client
- [x] Allow removing of cache

If you've any other suggestions, feel free to mention them in this topic.

**Comment by Fryslan** [comment]
Swing or JavaFX?

**Comment by SandroCoutinho** [comment]
In my opinion JavaFX would look better in this case.

**Comment by Fryslan** [comment]
agreed @CapslockRSPS
